version: "2"

services:
  consul:
    command: -server -client 0.0.0.0 -bootstrap --data-dir /var/consul -ui
    image: gliderlabs/consul-agent:0.6
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:53/udp
      - 192.168.50.4:53:53/udp
  swarm_master:
    image: swarm
    container_name: swarm_master
    networks:
      - app
    links:
      - consul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4000:4000"
    command: manage -H 0.0.0.0:4000 --replication --replication-ttl "4s" --advertise 192.168.50.4:4000 consul://192.168.50.4:8500
  swarm_node1:
    image: swarm
    container_name: swarm_node1
    networks:
      - app
    links:
      - consul
      - swarm_master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: join --advertise=192.168.50.4:2375 consul://192.168.50.4:8500
  registrator:  
    command:  -ip=192.168.50.4 consul://192.168.50.4:8500
    image: gliderlabs/registrator:latest
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
  example_app:
    image: hello-world
    networks:
      - app
    links:
      - consul
      - swarm_master

networks:
  app:
    driver: bridge