version: "2"

services:
  lb:
    image: hanzel/load-balancing-swarm
    container_name: lb
    networks:
      - weave
    ports:
      - "80:80"
    environment:
      - APP_NAME=nginx_web
      - CONSUL_URL=${KV_IP}:8500
    depends_on:
      - web
  web:
    image: nginx:stable-alpine
    restart: always
    networks:
      - weave
    ports:
      - "80"
      - "443"

networks:
  weave:
    external:
      name: weave