version: "2"

services:
  swarm_node2:
    image: swarm
    container_name: swarm_node2
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: join --advertise 172.17.8.102:2376 consul://172.17.8.101:8500
